---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tailscale
resources:
  - secrets.yaml
helmCharts:
  - name: tailscale-operator
    releaseName: tailscale-operator
    repo: https://pkgs.tailscale.com/helmcharts
    version: 1.94.2
    namespace: tailscale
    valuesInline:
      includeCRDs: true
      oauthSecretVolume:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: tailscale-operator-oauth
